version: '{build}'
image: Visual Studio 2019
branches:
  only:
  - master
build_script:
- ps: .\build.ps1
test: off

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: dFcmS+mlxTX3gzuewhTXCEeDTtZTTNx4jJox+Gg7s5crfdZj0jKzJYDqwusg7gFp
  on:
    branch: master
    appveyor_repo_tag: true

- provider: NuGet
  name: pre-release
  api_key:
    secure: nZHO3MlU3tR9ATVQIwsJKWwyALW3YVdmhgP+09+xhE9AVxDh9PwI+ZS/R1zq+tbr
  skip_symbols: true
  # on:
  #   branch: master

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
